INFO:uvicorn.error:Started server process [1431]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[0:3]
DEBUG:multipart.multipart:Calling on_field_data with data[4:5]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[6:7]
DEBUG:multipart.multipart:Calling on_field_data with data[8:9]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[10:11]
DEBUG:multipart.multipart:Calling on_field_data with data[12:13]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[14:16]
DEBUG:multipart.multipart:Calling on_field_data with data[17:18]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[19:21]
DEBUG:multipart.multipart:Calling on_field_data with data[22:25]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[26:30]
DEBUG:multipart.multipart:Calling on_field_data with data[31:34]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[35:37]
DEBUG:multipart.multipart:Calling on_field_data with data[38:41]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[42:44]
DEBUG:multipart.multipart:Calling on_field_data with data[45:48]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[49:51]
DEBUG:multipart.multipart:Calling on_field_data with data[52:55]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [1431]
INFO:uvicorn.error:Started server process [1736]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
ERROR:uvicorn.error:[Errno 98] error while attempting to bind on address ('127.0.0.1', 8000): address already in use
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Started server process [1954]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
ERROR:uvicorn.error:[Errno 98] error while attempting to bind on address ('127.0.0.1', 8000): address already in use
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Started server process [2044]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
ERROR:uvicorn.error:[Errno 98] error while attempting to bind on address ('127.0.0.1', 8000): address already in use
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Started server process [3330]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Finished server process [3330]
INFO:uvicorn.error:Started server process [3467]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[0:3]
DEBUG:multipart.multipart:Calling on_field_data with data[4:5]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[6:7]
DEBUG:multipart.multipart:Calling on_field_data with data[8:9]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[10:11]
DEBUG:multipart.multipart:Calling on_field_data with data[12:13]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[14:16]
DEBUG:multipart.multipart:Calling on_field_data with data[17:18]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[19:21]
DEBUG:multipart.multipart:Calling on_field_data with data[22:23]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[24:28]
DEBUG:multipart.multipart:Calling on_field_data with data[29:30]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[31:33]
DEBUG:multipart.multipart:Calling on_field_data with data[34:35]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[36:38]
DEBUG:multipart.multipart:Calling on_field_data with data[39:40]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[41:43]
DEBUG:multipart.multipart:Calling on_field_data with data[44:45]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[0:3]
DEBUG:multipart.multipart:Calling on_field_data with data[4:5]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[6:7]
DEBUG:multipart.multipart:Calling on_field_data with data[8:9]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[10:11]
DEBUG:multipart.multipart:Calling on_field_data with data[12:13]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[14:16]
DEBUG:multipart.multipart:Calling on_field_data with data[17:18]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[19:21]
DEBUG:multipart.multipart:Calling on_field_data with data[22:23]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[24:28]
DEBUG:multipart.multipart:Calling on_field_data with data[29:30]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[31:33]
DEBUG:multipart.multipart:Calling on_field_data with data[34:35]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[36:38]
DEBUG:multipart.multipart:Calling on_field_data with data[39:40]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[41:43]
DEBUG:multipart.multipart:Calling on_field_data with data[44:45]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[0:3]
DEBUG:multipart.multipart:Calling on_field_data with data[4:5]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[6:7]
DEBUG:multipart.multipart:Calling on_field_data with data[8:9]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[10:11]
DEBUG:multipart.multipart:Calling on_field_data with data[12:13]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[14:16]
DEBUG:multipart.multipart:Calling on_field_data with data[17:18]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[19:21]
DEBUG:multipart.multipart:Calling on_field_data with data[22:23]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[24:28]
DEBUG:multipart.multipart:Calling on_field_data with data[29:30]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[31:33]
DEBUG:multipart.multipart:Calling on_field_data with data[34:35]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[36:38]
DEBUG:multipart.multipart:Calling on_field_data with data[39:40]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_field_start with no data
DEBUG:multipart.multipart:Calling on_field_name with data[41:43]
DEBUG:multipart.multipart:Calling on_field_data with data[44:45]
DEBUG:multipart.multipart:Calling on_field_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
INFO:uvicorn.error:Started server process [8332]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Started server process [698]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [698]
INFO:uvicorn.error:Started server process [872]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "./src/app/main.py", line 56, in main
    "graph_data": graph_data,
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/templating.py", line 86, in TemplateResponse
    template = self.get_template(name)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/templating.py", line 73, in get_template
    return self.env.get_template(name)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "src/templates/home.html", line 7, in template
    {% block gchart}
jinja2.exceptions.TemplateSyntaxError: unexpected '}'
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [872]
INFO:uvicorn.error:Started server process [1008]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [1008]
INFO:uvicorn.error:Started server process [1182]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [1182]
INFO:uvicorn.error:Started server process [1321]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "./src/app/main.py", line 63, in main
    "graph_data2": graph_data2,
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/templating.py", line 93, in TemplateResponse
    background=background,
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/templating.py", line 33, in __init__
    content = template.render(context)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "src/templates/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "src/templates/base.html", line 12, in top-level template code
    {% block gchart %}{% endblock %}
  File "src/templates/home.html", line 15, in block 'gchart'
    {{graph_data1| tojson}}
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/filters.py", line 1673, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/utils.py", line 736, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "/home/unp1n99u/.pyenv/versions/3.6.15/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/unp1n99u/.pyenv/versions/3.6.15/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/unp1n99u/.pyenv/versions/3.6.15/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/unp1n99u/.pyenv/versions/3.6.15/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Undefined' is not JSON serializable
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "./src/app/main.py", line 63, in main
    "graph_data2": graph_data2,
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/templating.py", line 93, in TemplateResponse
    background=background,
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/templating.py", line 33, in __init__
    content = template.render(context)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "src/templates/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "src/templates/base.html", line 12, in top-level template code
    {% block gchart %}{% endblock %}
  File "src/templates/home.html", line 15, in block 'gchart'
    {{graph_data1| tojson}}
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/filters.py", line 1673, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/utils.py", line 736, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "/home/unp1n99u/.pyenv/versions/3.6.15/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/unp1n99u/.pyenv/versions/3.6.15/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/unp1n99u/.pyenv/versions/3.6.15/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/unp1n99u/.pyenv/versions/3.6.15/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Undefined' is not JSON serializable
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Finished server process [1321]
INFO:uvicorn.error:Started server process [1499]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [1499]
INFO:uvicorn.error:Started server process [1625]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [1625]
INFO:uvicorn.error:Started server process [1671]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [1671]
INFO:uvicorn.error:Started server process [1734]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [1734]
INFO:uvicorn.error:Started server process [1810]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [1810]
INFO:uvicorn.error:Started server process [3101]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [3101]
INFO:uvicorn.error:Started server process [3177]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [3177]
INFO:uvicorn.error:Started server process [3269]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [3269]
INFO:uvicorn.error:Started server process [3489]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [3489]
INFO:uvicorn.error:Started server process [4285]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [4285]
INFO:uvicorn.error:Started server process [4557]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:110]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[112:124]
DEBUG:multipart.multipart:Calling on_header_value with data[126:150]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[154:1151]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "./src/app/main.py", line 92, in predict
    data_scaled = scaler.transform(df.drop(['D', 'GT'], 1))
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/pandas/core/frame.py", line 4174, in drop
    errors=errors,
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/pandas/core/generic.py", line 3889, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/pandas/core/generic.py", line 3923, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 5287, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['D' 'GT'] not found in axis"
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:110]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[112:124]
DEBUG:multipart.multipart:Calling on_header_value with data[126:150]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[154:1151]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "./src/app/main.py", line 92, in predict
    data_scaled = scaler.transform(df.drop(['D', 'GT'], 1))
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/pandas/core/frame.py", line 4174, in drop
    errors=errors,
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/pandas/core/generic.py", line 3889, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/pandas/core/generic.py", line 3923, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 5287, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['D' 'GT'] not found in axis"
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [4557]
INFO:uvicorn.error:Started server process [4742]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:110]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[112:124]
DEBUG:multipart.multipart:Calling on_header_value with data[126:150]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[154:1151]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "./src/app/main.py", line 92, in predict
    data_scaled = scaler.transform(df)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/sklearn/preprocessing/_data.py", line 435, in transform
    force_all_finite="allow-nan", reset=False)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/sklearn/base.py", line 421, in _validate_data
    X = check_array(X, **check_params)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/sklearn/utils/validation.py", line 673, in check_array
    array = np.asarray(array, order=order, dtype=dtype)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/pandas/core/generic.py", line 1781, in __array__
    return np.asarray(self._values, dtype=dtype)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not convert string to float: 'INPUT_80_1'
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [4742]
INFO:uvicorn.error:Started server process [4850]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:110]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[112:124]
DEBUG:multipart.multipart:Calling on_header_value with data[126:150]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[154:1151]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "./src/app/main.py", line 92, in predict
    data_scaled = scaler.transform(df.drop('ID'))
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/pandas/core/frame.py", line 4174, in drop
    errors=errors,
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/pandas/core/generic.py", line 3889, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/pandas/core/generic.py", line 3923, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 5287, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['ID'] not found in axis"
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [4850]
INFO:uvicorn.error:Started server process [4966]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [4966]
INFO:uvicorn.error:Started server process [5074]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:110]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[112:124]
DEBUG:multipart.multipart:Calling on_header_value with data[126:150]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[154:1151]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "./src/app/main.py", line 120, in predict
    df_output.to_csv("./data/output.csv", index=False)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/pandas/core/generic.py", line 3170, in to_csv
    formatter.save()
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 190, in save
    compression=dict(self.compression_args, method=self.compression),
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/pandas/io/common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
FileNotFoundError: [Errno 2] No such file or directory: './data/output.csv'
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [5074]
INFO:uvicorn.error:Started server process [5182]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:110]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[112:124]
DEBUG:multipart.multipart:Calling on_header_value with data[126:150]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[154:1151]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "./src/app/main.py", line 132, in predict
    "graph_data1": graph_data2,
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/templating.py", line 86, in TemplateResponse
    template = self.get_template(name)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/templating.py", line 73, in get_template
    return self.env.get_template(name)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "src/templates/prediction.html", line 11, in template
    {% block page_title%}
jinja2.exceptions.TemplateAssertionError: block 'page_title' defined twice
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:110]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[112:124]
DEBUG:multipart.multipart:Calling on_header_value with data[126:150]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[154:1151]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [5182]
INFO:uvicorn.error:Started server process [5361]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:110]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[112:124]
DEBUG:multipart.multipart:Calling on_header_value with data[126:150]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[154:1151]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "./src/app/main.py", line 132, in predict
    "graph_data1": graph_data2,
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/templating.py", line 93, in TemplateResponse
    background=background,
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/templating.py", line 33, in __init__
    content = template.render(context)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "src/templates/prediction.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "src/templates/base.html", line 12, in top-level template code
    {% block gchart %}{% endblock %}
  File "src/templates/prediction.html", line 19, in block 'gchart'
    {{graph_data2| tojson}}
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/filters.py", line 1673, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/utils.py", line 736, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "/home/unp1n99u/.pyenv/versions/3.6.15/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/unp1n99u/.pyenv/versions/3.6.15/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/unp1n99u/.pyenv/versions/3.6.15/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/unp1n99u/.pyenv/versions/3.6.15/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Undefined' is not JSON serializable
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [5361]
INFO:uvicorn.error:Started server process [5509]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:110]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[112:124]
DEBUG:multipart.multipart:Calling on_header_value with data[126:150]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[154:829]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_data with data[831:1151]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "./src/app/main.py", line 132, in predict
    "graph_data1": graph_data2,
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/templating.py", line 93, in TemplateResponse
    background=background,
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/starlette/templating.py", line 33, in __init__
    content = template.render(context)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "src/templates/prediction.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "src/templates/base.html", line 12, in top-level template code
    {% block gchart %}{% endblock %}
  File "src/templates/prediction.html", line 19, in block 'gchart'
    {{graph_data2| tojson}}
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/filters.py", line 1673, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
  File "/mnt/d/User/jkhair/aiship_webapp/aishipwebappenv/lib/python3.6/site-packages/jinja2/utils.py", line 736, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "/home/unp1n99u/.pyenv/versions/3.6.15/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/unp1n99u/.pyenv/versions/3.6.15/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/unp1n99u/.pyenv/versions/3.6.15/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/unp1n99u/.pyenv/versions/3.6.15/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Undefined' is not JSON serializable
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [5509]
INFO:uvicorn.error:Started server process [5659]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:110]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[112:124]
DEBUG:multipart.multipart:Calling on_header_value with data[126:150]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[154:1151]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:110]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[112:124]
DEBUG:multipart.multipart:Calling on_header_value with data[126:150]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[154:1151]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:110]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[112:124]
DEBUG:multipart.multipart:Calling on_header_value with data[126:150]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[154:1151]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:110]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[112:124]
DEBUG:multipart.multipart:Calling on_header_value with data[126:150]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[154:1151]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:110]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[112:124]
DEBUG:multipart.multipart:Calling on_header_value with data[126:150]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[154:1151]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:110]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[112:124]
DEBUG:multipart.multipart:Calling on_header_value with data[126:150]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[154:1151]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:110]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[112:124]
DEBUG:multipart.multipart:Calling on_header_value with data[126:150]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[154:1151]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:110]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[112:124]
DEBUG:multipart.multipart:Calling on_header_value with data[126:150]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[154:1151]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:110]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[112:124]
DEBUG:multipart.multipart:Calling on_header_value with data[126:150]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[154:1151]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:110]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[112:124]
DEBUG:multipart.multipart:Calling on_header_value with data[126:150]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[154:1151]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:110]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[112:124]
DEBUG:multipart.multipart:Calling on_header_value with data[126:150]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[154:1151]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:110]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[112:124]
DEBUG:multipart.multipart:Calling on_header_value with data[126:150]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[154:1151]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:110]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[112:124]
DEBUG:multipart.multipart:Calling on_header_value with data[126:150]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[154:1151]
DEBUG:multipart.multipart:Calling on_part_data with data[0:2]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
